# Generated by Django 4.2.3 on 2023-09-07 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing_list', '0002_client_created_client_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создан'),
        ),
    ]