# Generated by Django 4.2.3 on 2023-09-07 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0004_alter_client_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('last_name',), 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
    ]