# Generated by Django 4.2.3 on 2023-09-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0005_alter_client_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailinglistmessage',
            old_name='created',
            new_name='created_time',
        ),
    ]